apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
type: Opaque
stringData:
  SUPABASE_URL: "add-your-supabase-url-here"
  SUPABASE_ANON_KEY: "add-your-supabase-anon-key-here"
  SUPABASE_SERVICE_KEY: "add-your-supabase-service-key-here"
